# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  deploy-to-hub:
    docker:
      - image: cimg/base:stable
    steps:
      - setup_remote_docker:
          version: 20.10.14
      - checkout
      - run:
          name: "Update"
          command: |
            sudo apt-get update
      - run:
          name: "Build Docker Images and Push to Hub"
          command: |
            curl -sL https://deb.nodesource.com/setup_14.x | sudo bash -
            sudo apt-get install -y nodejs
            echo "Install Node successfull"
            npm -v
            node -v
            echo "Building....."
            docker build -t udagram-api-feed ./udagram-api-feed
            docker tag udagram-api-feed khoangothe/udagram-api-feed:v1

            docker build -t udagram-api-user ./udagram-api-user
            docker tag udagram-api-user khoangothe/udagram-api-user:v1

            docker build -t udagram-frontend ./udagram-frontend
            docker tag udagram-frontend khoangothe/udagram-frontend:v1

            docker build -t udagram-reverseproxy ./udagram-reverseproxy
            docker tag udagram-reverseproxy khoangothe/udagram-reverseproxy:v1
            
            echo "Build Successful"
            docker login -u $USERNAME -p $PASSWORD
            echo "Pushing to hub"
            docker push khoangothe/udagram-api-feed:v1
            docker push khoangothe/udagram-api-user:v1
            docker push khoangothe/udagram-frontend:v1
            docker push khoangothe/udagram-reverseproxy:v1

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  deploy-to-hub-workflow:
    jobs:
      - deploy-to-hub

